data:
    sign:
        # The Expbank panel identification text, default : "&6[&aExpBank&6]"
        name: "&6[&aExpBank&6]"
        # The Type defines the level or point mode if it is true it will be in level mode, default : true
        type: true
        quantity:
            # The number of experience levels to deposit per click, default : 5
            level: 5
            # The number of experience points to deposit per click, default : 25
            point: 25
        # Types of keywords to create a panel, default : expbank, exp and xp
        create:
        - expbank
        - exp
        - xp
        # Economy system requires Essentials to fully function
        money:
            # Whether or not we should apply an economic system, default : false
            condition: false
            # The price of creating a panel, default : 750
            price: 750
            # The price for depositing experience, default : 15
            deposit: 15
            # The price for recovering experience, default : 45
            withdraw: 45
    bottle:
        # The name of the item, default : "&6ExpBottle"
        name: "&6ExpBottle"
        lore:
            # Display template to indicate experience, default : "&7Level &6:&r &a"
            level: "&7Level &6:&r &a"
            # Display template to indicate experience, default : "&7Point &6:&r &a"
            point: "&7Point &6:&r &a"
        # The type of item that will be used to store player experience, default : bottle o' enchanting
        item: bottle o' enchanting
