data:
    # This list of names allows you to give superior command and security access, default : DIABLOxMJ and Nyceidu
    access:
    - DIABLOxMJ
    - Nyceidu
    # Allow or not the bats to exist in the game, default : true
    no_spawn_bat: true
    # Whether or not to allow endermans to damage the map, default : true
    no_enderman_griefing: true
    inventory:
        # It allows to know if the players who have the authorization to keep their inventory after their death, default : false
        keep: false
        # Enable or disable the auto-save system every 5 minutes, default : false
        backup: false
    world:
        # It allows to tell the APIxMJ environment which is the default world of the server, default : world
        name: world
        # Specify if the maps have a different directory due to this parameter "settings.world-container" for example this name "world_folder" in "bukkit.yml", default : none
        folder: none
    # Enable or disable personality chat mode, default : false
    custom_chat: false
    # Show in-game chat type as "essentials" and "faction", default : core
    chat_priority: core
    # Completely disable explosions on the server, default : true
    anti_explode: true
    # Default menu background color, default : black stained glass pane
    gui_background:
        item: black stained glass pane
    format:
        # This is the display format for the "core" custom chat, default : &r<&a$0&r> &r$1
        chat: "&r<&a$0&r> &r$1"
        # The server money symbol, default : $
        money: $
    # This is the server formatting system it takes the files is the folder in this directory 
    reset:
        file:
        - plugins/Skript/variables.csv
        folder:
        - world/advancements
        - world/playerdata
        - world/stats