data:
    heat_wave:
        # Whether or not we allow this system to work, default : false
        condition: false
        # The percentage chance that the helmet being used will be damaged, default : 5
        chance_of_damage_helmet: 5
        # The amount of damage to inflict on the player, default : 0.5
        damage_player: 0.5
    respawn_penalty:
        # Whether or not we allow this system to work, default : false
        condition: false
        # The number of possible deaths before a temporary ban, default : 5
        chance_before_banned: 5
        # The duration of the ban, default : 1h
        time_banned: 1h
    sword_of_skeleton:
        # Whether or not we allow this system to work, default : false
        condition: false
        # The percentage chance that a skeleton spawns with a sword, default : 50
        chance_of_spawn: 50
        # The item that will be given, default : iron sword
        item: iron sword