# =====================================================================================================================
# APIxMJ - Installer
# ---------------------------------------------------------------------------------------------------------------------
on load:
	send "[APIxMJ] Installing language..." to console
	send "[APIxMJ] Setup..." to console
	set {_type} to "ranker"
	set {_folder} to mj_editfiles("manager.data", "data.addon.vertebral_main.%{_type}%.folder")
	mj_install_config({_folder}, {_type})
	mj_install_data({_folder}, {_type})
	send "[APIxMJ] Finish..." to console
	delete file "plugins/Skript/scripts/apixmj_update.sk"
	unload script file "apixmj_update.sk"
	stop
# ---------------------------------------------------------------------------------------------------------------------
# APIxMJ - Installer
# =====================================================================================================================
# APIxMJ - Config
# ---------------------------------------------------------------------------------------------------------------------
function mj_install_config(folder: text, type: text):
	set {_source} to "mj.%{_type}%.config"
	set {_01} to yaml value "data" from "%{_source}%"
	wait 5 ticks
	mj_manager_file_reset({_folder}, "config")
	wait 5 ticks
	set yaml value "data" from "%{_source}%" to {_01}
	save yaml "%{_source}%"
	stop
# ---------------------------------------------------------------------------------------------------------------------
# APIxMJ - Config
# =====================================================================================================================
# APIxMJ - Data
# ---------------------------------------------------------------------------------------------------------------------
function mj_install_data(folder: text, type: text):
	set {_source} to "mj.%{_type}%.data"
	set {_01} to yaml value "data" from "%{_source}%"
	wait 5 ticks
	mj_manager_file_reset({_folder}, "data")
	wait 5 ticks
	set yaml value "data" from "%{_source}%" to {_01}
	save yaml "%{_source}%"
	stop
# ---------------------------------------------------------------------------------------------------------------------
# APIxMJ - Data
# =====================================================================================================================