data:
    # This list of names allows you to give superior command and security access, default : DIABLOxMJ and Nyceidu
    access:
    - DIABLOxMJ
    - Nyceidu
    # Allow or not the bats to exist in the game, default : true
    no_spawn_bat: true
    # Whether or not to allow endermans to damage the map, default : true
    no_enderman_griefing: true
    world:
        # It allows to tell the APIxMJ environment which is the default world of the server, default : world
        name: world
        # Specify if the maps have a different directory due to this parameter "settings.world-container" for example this name "world_folder" in "bukkit.yml", default : none
        folder: none
    # Enable or disable personality chat mode, default : false
    custom_chat: false
    # Show in-game chat type as "essentials" and "faction", default : core
    chat_priority: core
    # Completely disable explosions on the server, default : true
    anti_explode: true
    # Default menu background color, default : black stained glass pane
    gui_background:
        item: black stained glass pane
    format:
        # This is the display format for the "core" custom chat, default : &r<&a$0&r> &r$1
        chat: "&r<&a$0&r> &r$1"
        money:
            # The server money symbol, default : $
            symbol: $
            # The server price pourcent model, default : "&a<money>&6/&a<limit> &6(&a<pourcent>%&6)"
            pourcent: "&a<money>&6/&a<limit> &6(&a<pourcent>%&6)"
            # The server price taxe model, default : "&a<money> &6(&7taxe of &a<pourcent>%&6)"
            taxe: "&a<money> &6(&7taxe of &a<pourcent>%&6)"
            # The server price discount model, default : "&a<money> &6(&7discount of &a<pourcent>%&6)"
            discount: "&a<money> &6(&7discount of &a<pourcent>%&6)"
        progress_bar:
            '0': "&f▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
            '5': "&a▬&f▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
            '10': "&a▬▬&f▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
            '15': "&a▬▬▬&f▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
            '20': "&a▬▬▬▬&f▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
            '25': "&a▬▬▬▬▬&f▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
            '30': "&a▬▬▬▬▬▬&f▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
            '35': "&a▬▬▬▬▬▬▬&f▬▬▬▬▬▬▬▬▬▬▬▬▬"
            '40': "&a▬▬▬▬▬▬▬▬&f▬▬▬▬▬▬▬▬▬▬▬▬"
            '45': "&a▬▬▬▬▬▬▬▬▬&f▬▬▬▬▬▬▬▬▬▬▬"
            '50': "&a▬▬▬▬▬▬▬▬▬▬&f▬▬▬▬▬▬▬▬▬▬"
            '55': "&a▬▬▬▬▬▬▬▬▬▬▬&f▬▬▬▬▬▬▬▬▬"
            '60': "&a▬▬▬▬▬▬▬▬▬▬▬▬&f▬▬▬▬▬▬▬▬"
            '65': "&a▬▬▬▬▬▬▬▬▬▬▬▬▬&f▬▬▬▬▬▬▬"
            '70': "&a▬▬▬▬▬▬▬▬▬▬▬▬▬▬&f▬▬▬▬▬▬"
            '75': "&a▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬&f▬▬▬▬▬"
            '80': "&a▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬&f▬▬▬▬"
            '85': "&a▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬&f▬▬▬"
            '90': "&a▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬&f▬▬"
            '95': "&a▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬&f▬"
            '100': "&a▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
    # This is the server formatting system it takes the files is the folder in this directory 
    reset:
        file:
        - plugins/Skript/variables.csv
        folder:
        - world/advancements
        - world/playerdata
        - world/stats