data:
    object:
        # The name of the item, default : "&aBackpack"
        name: "&aBackpack"
        lore: 
            # The description that will be used to store the size, default : "&7Tiers &6: &a"
            '1': "&7Tiers &6: &a"
            # The description that will be used to store the id, default : "&7UUID &6: &a"
            '2': "&7UUID &6: &a"
            # The description that will be used to store the owner, default : "&7Owner &6: &a"
            '3': "&7Owner &6: &a"
        # The item that will be used, default : brown shulker box
        item: brown shulker box